### ISSUE TITLE
Infokarte

### ISSUE THREAD

**Issue by kurobrob** [Schkai/d3-Marvel-Who-is-who#13]
Infobox über ausgewählten Character rechts neben der Visualisierung.

**Comment by kurobrob** [comment]
Infobox (Bootstrap Card) des ausgewählten Charakters erscheint in der Mitte des Diagramms.

**Comment by Schkai** [comment]
Die Karte wird angezeigt, aber irgendwas verdeckt die darunter liegende Ansicht der einzelnen Nodes, sodass jetzt eine weiße Fläche anstatt den Verbindungen ist. Kannst du das fixen?

Für die Karte wäre dann wohl ein Background mit einer geringen Opacity gut.
Siehe: https://stackoverflow.com/questions/10422949/css-background-opacity
