### ISSUE TITLE
marvel-daten matchen

### ISSUE THREAD

**Issue by EliasDerHai** [Schkai/d3-Marvel-Who-is-who#4]
charaktere nach jahr matchen und in json speichern
evtl: 
characterRelations.json:
{"name":"Batman","year":"1975","meets":["Heroxy","Heroxy2",...]}
{"name":"Batman","year":"1976","meets":["Heroxy3","Heroxy5",...]}

**Comment by k3k5** [comment]
@EliasDerHai @Schkai @kurobrob Gerade habe ich die Python-Implementierung fertiggestellt. Schaut es euch mal an ob es so passt, dann könnte ich wenn es denn wäre am Sonntag nochmal mit der Feile ran. Aktuell besteht nur noch das Problem, dass ich keine Ahnung hab, wie ich das Limit mit den 100 Charactern / Events umgehen kann. Wenn da jemand von euch noch nen schlauen Einfall hätte wäre ich ultra dankbar!!!!!
Der Code kann manuell ausgeführt werden, indem ihr zum python directory navigiert und dann in der Command Line / Terminal mittels `python3 main.py`das Script startet. Aktuell ist mein API Key hinterlegt, das könntet ihr, wenn ihr wollt, ebenfalls in der main.py abändern (Variablen: `PRIV_KEY` und `PUBLIC_KEY`).
Um das Script starten zu können, müsst ihr logischerweise Python3 installiert haben... Solltet ihr das nicht haben, hier ist der Link: https://www.python.org/downloads/
